# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d636fdd74803f8acf44fad239c1338729c48e35451429450dff14d5a534dcf43026c416ace7583182a8020b6878c9fbd3891784515ff9601fbeb6a66075a24be

test:
  secret_key_base: 4d09e61cf267f0b4689985270837bc036c1d958b4822d8d30673d9aae600cfc52c2fc66745a69abab79d38f66cd494bbf556b230c665e1724af68d8ac0201e88

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
